#! /bin/sh

sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo systemctl disable rsyslog.service

sudo apt-get update
sudo apt-get upgrade

sudo apt-get -y install language-pack-ru language-pack-ru-base
sudo locale-gen ru_RU.CP1251
sudo locale-gen ru_RU.UTF-8
sudo update-locale
sudo dpkg-reconfigure tzdata
sudo apt-get -y install ubuntu-restricted-extras
sudo apt-get -y install postgresql-client libpq-dev
sudo apt-get -y install default-jdk
sudo apt-get -y install git build-essential gcc pkg-config cmake libssl-dev libffi-dev libgmp3-dev vim tmux mc htop
sudo apt-get -y install openssh-server sshfs openvpn easy-rsa nfs-common net-tools curl remmina freerdp2-x11
sudo apt-get -y install gpart gparted exfat-fuse exfatprogs testdisk clonezilla
sudo apt-get -y install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract file-roller pbzip2 archivemount
sudo apt-get -y install smbclient cifs-utils
sudo apt-get -y install gimp gimp-data gimp-plugin-registry gimp-data-extras vlc audacity xsane dia inkscape ffmpeg
sudo apt-get -y install openshot-qt
sudo apt-get -y install libreoffice libreoffice-l10n-ru libreoffice-help-ru libreoffice-base libreoffice-sdbc-postgresql
sudo apt-get -y install cups printer-driver-all
sudo apt-get -y install brasero
sudo apt-get -y install nmap nmapsi4

sudo apt-get -y install gnome-disk-utility
#sudo apt-get install gnome-calculator gnome-tweak-tool gnome-shell-extension-manager gnome-shell-extensions menulibre

sudo apt-get -y install qemu qemu-kvm bridge-utils virt-manager virt-viewer ssh-askpass
#sudo apt-get install virtualbox-6.1

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt -y autoremove
